/**
 * Diagram Theme Configurations
 * Defines visual styles for different diagram themes
 */

import { DiagramThemeConfig, DiagramThemeName } from "./types";

export const diagramThemes: Record<DiagramThemeName, DiagramThemeConfig> = {
  minimal: {
    name: "Minimal",
    nodeColors: {
      start: "#4A90E2",
      process: "#7B68EE",
      decision: "#FF6B6B",
      end: "#50C878",
      root: "#4A90E2",
      child: "#95A5A6",
      entity: "#3498DB",
      class: "#9B59B6",
      state: "#E74C3C",
    },
    edgeColor: "#BDC3C7",
    edgeWidth: 2,
    backgroundColor: "#FFFFFF",
    gridColor: "#F5F5F5",
    glowEffect: false,
    borderStyle: "solid",
  },
  neon: {
    name: "Neon",
    nodeColors: {
      start: "#00FFFF",
      process: "#FF00FF",
      decision: "#FFFF00",
      end: "#00FF00",
      root: "#00FFFF",
      child: "#FF1493",
      entity: "#00CED1",
      class: "#FF69B4",
      state: "#FFD700",
    },
    edgeColor: "#FF00FF",
    edgeWidth: 3,
    backgroundColor: "#0A0A0A",
    gridColor: "#1A1A1A",
    glowEffect: true,
    borderStyle: "solid",
  },
  cyberpunk: {
    name: "Cyberpunk",
    nodeColors: {
      start: "#00F5FF",
      process: "#FF0080",
      decision: "#FFD700",
      end: "#39FF14",
      root: "#00F5FF",
      child: "#FF1493",
      entity: "#00CED1",
      class: "#FF69B4",
      state: "#FFD700",
    },
    edgeColor: "#FF0080",
    edgeWidth: 2,
    backgroundColor: "#0D1117",
    gridColor: "#161B22",
    glowEffect: true,
    borderStyle: "solid",
  },
  pastel: {
    name: "Pastel",
    nodeColors: {
      start: "#B4E4FF",
      process: "#FFB4E1",
      decision: "#FFE4B4",
      end: "#B4FFB4",
      root: "#B4E4FF",
      child: "#E4B4FF",
      entity: "#B4E4FF",
      class: "#FFB4E1",
      state: "#FFE4B4",
    },
    edgeColor: "#D4D4D4",
    edgeWidth: 2,
    backgroundColor: "#FFF9F0",
    gridColor: "#F5F5F5",
    glowEffect: false,
    borderStyle: "solid",
  },
  blueprint: {
    name: "Blueprint",
    nodeColors: {
      start: "#1E3A8A",
      process: "#1E40AF",
      decision: "#3B82F6",
      end: "#60A5FA",
      root: "#1E3A8A",
      child: "#3B82F6",
      entity: "#1E40AF",
      class: "#2563EB",
      state: "#3B82F6",
    },
    edgeColor: "#3B82F6",
    edgeWidth: 2,
    backgroundColor: "#EFF6FF",
    gridColor: "#DBEAFE",
    glowEffect: false,
    borderStyle: "dashed",
  },
  techwire: {
    name: "Techwire",
    nodeColors: {
      start: "#10B981",
      process: "#3B82F6",
      decision: "#F59E0B",
      end: "#EF4444",
      root: "#10B981",
      child: "#6B7280",
      entity: "#3B82F6",
      class: "#8B5CF6",
      state: "#F59E0B",
    },
    edgeColor: "#6B7280",
    edgeWidth: 2,
    backgroundColor: "#F9FAFB",
    gridColor: "#E5E7EB",
    glowEffect: false,
    borderStyle: "solid",
  },
  professional_office: {
    name: "Professional Office",
    nodeColors: {
      start: "#2563EB",
      process: "#7C3AED",
      decision: "#DC2626",
      end: "#059669",
      root: "#2563EB",
      child: "#64748B",
      entity: "#2563EB",
      class: "#7C3AED",
      state: "#DC2626",
    },
    edgeColor: "#94A3B8",
    edgeWidth: 2,
    backgroundColor: "#FFFFFF",
    gridColor: "#F1F5F9",
    glowEffect: false,
    borderStyle: "solid",
  },
};

export function getTheme(themeName: DiagramThemeName): DiagramThemeConfig {
  return diagramThemes[themeName] || diagramThemes.minimal;
}

